package com.splitter.backend.event.model;

public enum GroupEventType {
    EXPENSE_CREATED,
    SETTLEMENT_CREATED,
    SETTLEMENT_CONFIRMED,
    SETTLEMENT_REJECTED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_PROMOTED,
    MEMBER_DEMOTED,
    GROUP_RENAMED,
    GROUP_ARCHIVED
}
